---
name: cov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
        files: ./coverage1.xml,./coverage2.xml  # optional
        flags: unittests  # optional
        name: codecov-umbrella  # optional
        fail_ci_if_error: true  # optional (default = false)
        verbose: true  # optional (default = false)
