---
name: main

on:
  push:
    branches: [main]
    paths-ignore: ["README.md", "docs/**"]
    tags:
  pull_request:

jobs:
  #  main-windows:
  #    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
  #    with:
  #      env: '["py37"]'
  #      os: windows-latest
  main-linux:
    tox:
      uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
      with:
        env: '["py37", "py38", "py39"]'
        os: ubuntu-latest
    cov:
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
          files: ./coverage.xml  # optional
          flags: unittests  # optional
          name: codecov-umbrella  # optional
          fail_ci_if_error: true  # optional (default = false)
          verbose: true  # optional (default = false)
